Document: pandorga-config-mate
Title: Debian pandorga-config-mate Manual
Author: <insert document author here>
Abstract: This manual describes what pandorga-config-mate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pandorga-config-mate/pandorga-config-mate.sgml.gz

Format: postscript
Files: /usr/share/doc/pandorga-config-mate/pandorga-config-mate.ps.gz

Format: text
Files: /usr/share/doc/pandorga-config-mate/pandorga-config-mate.text.gz

Format: HTML
Index: /usr/share/doc/pandorga-config-mate/html/index.html
Files: /usr/share/doc/pandorga-config-mate/html/*.html
